### ISSUE TITLE
Did not enable updates

### ISSUE THREAD

**Issue by ksanders12** [jv16x/UpdateFixer#2]
I have a Citrix Desktop VM.  UpdateFixer suggested to changes Those change or selecting all changes (add a select all button) did not enable the updates. 

![2023-01-25 15_38_48-Windows 10 Persistent Desktops - Desktop Viewer](https://user-images.githubusercontent.com/39716139/214697777-01516b4d-659d-4464-af1e-a5bf67211875.png)

**Comment by jv16x** [comment]
If you find out how Windows Update can be enabled in this system (it seems to be disabled by some settings), please let me know and I can add support for that to the app.
